version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 funetec_system.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=funetec_db
      - POSTGRES_USER=funetec_user
      - POSTGRES_PASSWORD=funetec_pass

volumes:
  postgres_data:
