version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 Pactum.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
