# Generated by Django 4.2.7 on 2025-09-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('cod_projeto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Projeto')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_encerramento', models.DateField(verbose_name='Data de Encerramento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Orçado')),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Realizado')),
                ('situacao', models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Paralisado'), ('4', 'Suspenso'), ('5', 'Cancelado'), ('6', 'Concluído')], default='1', max_length=20, verbose_name='Situação')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('cod_requisicao', models.AutoField(primary_key=True, serialize=False, verbose_name='Código da Requisição')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição da Requisição')),
                ('data_solicitacao', models.DateField(verbose_name='Data de Solicitação')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Requisição')),
                ('situacao', models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Suspensa'), ('4', 'Cancelada'), ('5', 'Concluída')], default='1', max_length=20, verbose_name='Situação')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='projetos.projeto', verbose_name='Projeto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('cod_ordem', models.AutoField(primary_key=True, serialize=False, verbose_name='Código da Ordem')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição da Ordem')),
                ('data_solicitacao', models.DateField(verbose_name='Data de Solicitação')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Ordem')),
                ('situacao', models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Cancelada'), ('4', 'Concluída')], default='1', max_length=20, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_requisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='projetos.requisicao', verbose_name='Requisição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
                ('executante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_executante', to=settings.AUTH_USER_MODEL, verbose_name='Executante')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cod_item', models.IntegerField(verbose_name='Código do Item')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição do Item')),
                ('data_solicitacao', models.DateField(verbose_name='Data de Solicitação')),
                ('data_limite', models.DateField(verbose_name='Data Limite de Entrega')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor do Item')),
                ('data_recebido', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('situacao', models.CharField(choices=[('1', 'Lançado'), ('2', 'Cancelado'), ('3', 'Entregue')], default='1', max_length=20, verbose_name='Situação')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Unitário')),
                ('cod_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='projetos.ordem', verbose_name='Ordem de Serviço')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Item da Ordem',
                'verbose_name_plural': 'Itens da Ordem',
                'ordering': ['cod_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemordem',
            constraint=models.CheckConstraint(check=models.Q(('data_limite__gte', models.F('data_solicitacao'))), name='item_ordem_data_limite_valida'),
        ),
        migrations.AddConstraint(
            model_name='itemordem',
            constraint=models.CheckConstraint(check=models.Q(('valor__gte', 0)), name='item_ordem_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itemordem',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gt', 0)), name='item_ordem_quantidade_positiva'),
        ),
        migrations.AlterUniqueTogether(
            name='itemordem',
            unique_together={('cod_ordem', 'cod_item')},
        ),
    ]
