# Generated by Django 4.2.7 on 2025-09-12 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0002_projeto_custo_previsto_projeto_custo_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='cod_ordem',
            field=models.IntegerField(db_column='codOrdem', primary_key=True, serialize=False, verbose_name='Código da Ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='cod_requisicao',
            field=models.ForeignKey(db_column='codRequisicao', on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='projetos.requisicao', verbose_name='Requisição'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_limite',
            field=models.DateField(db_column='dataLimite', verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(db_column='dataSolicitacao', verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cod_projeto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_encerramento',
            field=models.DateField(db_column='dataFim', verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(db_column='dataInicio', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(db_column='nomeProjeto', max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(db_column='responsavel', on_delete=django.db.models.deletion.PROTECT, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Paralisado'), ('4', 'Suspenso'), ('5', 'Cancelado'), ('6', 'Concluído')], default='1', max_length=20, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(db_column='valorTotal', decimal_places=2, max_digits=14, verbose_name='Valor Orçado'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='cod_projeto',
            field=models.ForeignKey(db_column='codProjeto', on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='projetos.projeto', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='cod_requisicao',
            field=models.IntegerField(db_column='codRequisicao', primary_key=True, serialize=False, verbose_name='Código da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_limite',
            field=models.DateField(db_column='dataLimite', verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_solicitacao',
            field=models.DateField(db_column='dataSolicitacao', verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=10, null=True, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
