# Generated by Django 4.2.7 on 2025-09-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_ordem_cod_ordem_alter_ordem_cod_requisicao_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordem',
            table='ordem',
        ),
        migrations.AlterModelTable(
            name='projeto',
            table='projetos',
        ),
        migrations.AlterModelTable(
            name='requisicao',
            table='requisicao',
        ),
    ]
