# Generated by Django 4.2.7 on 2025-09-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_ordem_table_alter_projeto_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(db_column='descricao', max_length=500, verbose_name='Descrição da Ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Cancelada'), ('4', 'Concluída')], db_column='situacao', default='1', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='valor',
            field=models.DecimalField(db_column='valor', decimal_places=2, max_digits=14, verbose_name='Valor da Ordem'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cod_projeto',
            field=models.IntegerField(db_column='codProjeto', primary_key=True, serialize=False, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_encerramento',
            field=models.DateField(db_column='dataEncerramento', verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(db_column='nome', max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Paralisado'), ('4', 'Suspenso'), ('5', 'Cancelado'), ('6', 'Concluído')], db_column='situacao', default='1', max_length=20, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(db_column='valor', decimal_places=2, max_digits=14, verbose_name='Valor Orçado'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='descricao',
            field=models.CharField(db_column='descricao', max_length=500, verbose_name='Descrição da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Suspensa'), ('4', 'Cancelada'), ('5', 'Concluída')], db_column='situacao', default='1', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='valor',
            field=models.DecimalField(db_column='valor', decimal_places=2, max_digits=14, verbose_name='Valor da Requisição'),
        ),
    ]
