# Generated by Django 4.2.7 on 2025-09-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_ordem_descricao_alter_ordem_situacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemordem',
            options={'verbose_name': 'Item da Ordem', 'verbose_name_plural': 'Itens da Ordem'},
        ),
        migrations.AlterModelOptions(
            name='ordem',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='requisicao',
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisições'},
        ),
        migrations.RemoveConstraint(
            model_name='itemordem',
            name='item_ordem_data_limite_valida',
        ),
        migrations.RemoveConstraint(
            model_name='itemordem',
            name='item_ordem_valor_positivo',
        ),
        migrations.RemoveConstraint(
            model_name='itemordem',
            name='item_ordem_quantidade_positiva',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='itemordem',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='executante',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente_nome',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente_telefone',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='custo_previsto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='custo_realizado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valor_realizado',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='itemordem',
            name='cod_ordem',
            field=models.ForeignKey(db_column='codOrdem', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='projetos.ordem'),
        ),
        migrations.AlterField(
            model_name='itemordem',
            name='data_limite',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='itemordem',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='itemordem',
            name='situacao',
            field=models.CharField(choices=[('1', 'Lançado'), ('2', 'Cancelado'), ('3', 'Entregue')], max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='itemordem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='cod_ordem',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_limite',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Cancelada'), ('4', 'Concluída')], max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cod_projeto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Paralisado'), ('4', 'Suspenso'), ('5', 'Cancelado'), ('6', 'Concluído')], default='1', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Orçado'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='cod_requisicao',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_limite',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_solicitacao',
            field=models.DateField(verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Suspensa'), ('4', 'Cancelada'), ('5', 'Concluída')], max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor'),
        ),
        migrations.AlterModelTable(
            name='itemordem',
            table='itens_ordem',
        ),
    ]
