# Generated by Django 4.2.7 on 2025-09-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_itemordem_options_alter_ordem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='cod_ordem',
            field=models.IntegerField(db_column='codOrdem', primary_key=True, serialize=False, verbose_name='Código da Ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_limite',
            field=models.DateField(db_column='dataLimite', verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(db_column='dataSolicitacao', verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cod_projeto',
            field=models.IntegerField(db_column='codProjeto', primary_key=True, serialize=False, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_encerramento',
            field=models.DateField(db_column='dataEncerramento', verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(db_column='dataInicio', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='cod_requisicao',
            field=models.IntegerField(db_column='codRequisicao', primary_key=True, serialize=False, verbose_name='Código da Requisição'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_limite',
            field=models.DateField(db_column='dataLimite', verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_solicitacao',
            field=models.DateField(db_column='dataSolicitacao', verbose_name='Data de Solicitação'),
        ),
    ]
