# Generated by Django 4.2.7 on 2025-09-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('num_contrato', models.CharField(help_text='Formato: NNNN/AAAA (ex: 0001/2025)', max_length=10, primary_key=True, serialize=False, verbose_name='Número do Contrato')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição do Contrato')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ do Contratado')),
                ('contratado', models.CharField(max_length=150, verbose_name='Nome do Contratado')),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo de Pessoa')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor do Contrato')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('data_parcela_inicial', models.DateField(verbose_name='Data de Vencimento da Primeira Parcela')),
                ('situacao', models.CharField(choices=[('1', 'Lançado'), ('2', 'Em andamento'), ('3', 'Cancelado'), ('4', 'Finalizado')], default='1', max_length=20, verbose_name='Situação')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Líquido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pendente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_ordem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='projetos.ordem', verbose_name='Ordem de Serviço')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo de Pessoa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_lancamento', models.IntegerField(verbose_name='Código do Lançamento')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('num_parcela', models.IntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('situacao', models.CharField(choices=[('1', 'Lançado'), ('2', 'Cancelado'), ('3', 'Liquidado')], default='1', max_length=20, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
                'ordering': ['num_parcela'],
                'unique_together': {('num_contrato', 'cod_lancamento')},
            },
        ),
    ]
