# Generated by Django 4.2.7 on 2025-09-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontrato',
            name='situacao',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Cancelado'), ('3', 'Paga'), ('4', 'Parcialmente Paga')], default='1', max_length=20, verbose_name='Situação'),
        ),
    ]
