# Generated by Django 4.2.7 on 2025-09-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_itemcontrato_situacao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
        migrations.AlterModelTable(
            name='itemcontrato',
            table='item_contrato',
        ),
    ]
