# Generated by Django 4.2.7 on 2025-09-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_ordem_descricao_alter_ordem_situacao_and_more'),
        ('contratos', '0003_alter_contrato_table_alter_itemcontrato_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cod_ordem',
            field=models.OneToOneField(db_column='codOrdem', on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='projetos.ordem', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contratado',
            field=models.CharField(db_column='contratado', max_length=150, verbose_name='Nome do Contratado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf_cnpj',
            field=models.CharField(db_column='cpfCnpj', max_length=18, verbose_name='CPF/CNPJ do Contratado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(db_column='dataFim', verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(db_column='dataInicio', verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_parcela_inicial',
            field=models.DateField(db_column='dataParcelaInicial', verbose_name='Data de Vencimento da Primeira Parcela'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.CharField(db_column='objeto', max_length=500, verbose_name='Descrição do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='num_contrato',
            field=models.CharField(db_column='numContrato', help_text='Formato: NNNN/AAAA (ex: 0001/2025)', max_length=10, primary_key=True, serialize=False, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='parcelas',
            field=models.IntegerField(db_column='parcelas', default=1, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('1', 'Lançado'), ('2', 'Em andamento'), ('3', 'Cancelado'), ('4', 'Finalizado')], db_column='situacao', default='1', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_pessoa',
            field=models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], db_column='tipoPessoa', verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(db_column='valor', decimal_places=2, max_digits=14, verbose_name='Valor do Contrato'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='cod_lancamento',
            field=models.IntegerField(db_column='codLancamento', verbose_name='Código do Lançamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_lancamento',
            field=models.DateField(db_column='dataLancamento', verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_pagamento',
            field=models.DateField(blank=True, db_column='dataPagamento', null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_vencimento',
            field=models.DateField(db_column='dataVencimento', verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='num_contrato',
            field=models.ForeignKey(db_column='numContrato', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='num_parcela',
            field=models.IntegerField(db_column='numParcela', verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='observacoes',
            field=models.TextField(blank=True, db_column='observacoes', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='situacao',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Cancelado'), ('3', 'Paga'), ('4', 'Parcialmente Paga')], db_column='situacao', default='1', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='valor_pago',
            field=models.DecimalField(db_column='valorPago', decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='valor_parcela',
            field=models.DecimalField(db_column='valorParcela', decimal_places=2, max_digits=14, verbose_name='Valor da Parcela'),
        ),
    ]
