# Generated by Django 4.2.7 on 2025-09-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_cod_ordem_alter_contrato_contratado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestador',
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='itemcontrato',
            options={'verbose_name': 'Item do Contrato', 'verbose_name_plural': 'Itens do Contrato'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_liquido',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_pago',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_pendente',
        ),
        migrations.RemoveField(
            model_name='itemcontrato',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemcontrato',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='itemcontrato',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contratado',
            field=models.CharField(max_length=150, verbose_name='Contratado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf_cnpj',
            field=models.CharField(db_column='cpfcnpj', max_length=14, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_parcela_inicial',
            field=models.DateField(db_column='dataParcelaInicial', verbose_name='Data Parcela Inicial'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='num_contrato',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='parcelas',
            field=models.IntegerField(verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('1', 'Lançado'), ('2', 'Em andamento'), ('3', 'Cancelado'), ('4', 'Finalizado')], max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='cod_lancamento',
            field=models.IntegerField(verbose_name='Código do Lançamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_lancamento',
            field=models.DateField(verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='num_contrato',
            field=models.ForeignKey(db_column='numContrato', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='num_parcela',
            field=models.IntegerField(verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='situacao',
            field=models.CharField(choices=[('1', 'Lançado'), ('2', 'Cancelado'), ('3', 'Liquidado')], max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Parcela'),
        ),
        migrations.AlterModelTable(
            name='itemcontrato',
            table='itens_contrato',
        ),
    ]
