# Generated by Django 4.2.7 on 2025-09-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_delete_prestador_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(help_text='Nome completo para PF ou Razão Social para PJ', max_length=200, verbose_name='Nome/Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Apenas para PJ', max_length=200, verbose_name='Nome Fantasia')),
                ('cpf', models.CharField(blank=True, help_text='Apenas para PF', max_length=14, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, help_text='Apenas para PJ', max_length=18, unique=True, verbose_name='CNPJ')),
                ('rg', models.CharField(blank=True, help_text='Apenas para PF', max_length=20, verbose_name='RG')),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Apenas para PJ', max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, help_text='Para PJ que prestam serviços', max_length=20, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança')], max_length=20, verbose_name='Tipo de Conta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'db_table': 'prestador',
            },
        ),
    ]
