# Generated by Django 4.2.7 on 2025-09-12 23:57

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_prestador'),
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        # Adicionar campos do BaseModel e mixins
        migrations.AddField(
            model_name='contrato',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(default=timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='accounts.User',
                verbose_name='Criado por'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='accounts.User',
                verbose_name='Atualizado por'
            ),
        ),
        
        # Adicionar novos campos de negócio
        migrations.AddField(
            model_name='contrato',
            name='prestador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='contratos.prestador',
                verbose_name='Prestador',
                help_text='Prestador de serviços (PF ou PJ)'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_previsto',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=14,
                verbose_name='Valor Previsto',
                help_text='Valor total previsto do contrato'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_realizado',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=14,
                verbose_name='Valor Realizado',
                help_text='Valor já executado/entregue'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_pagamento',
            field=models.CharField(
                choices=[('unico', 'Pagamento Único'), ('parcelas', 'Pagamento em Parcelas')],
                default='parcelas',
                max_length=20,
                verbose_name='Tipo de Pagamento'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_parcelas',
            field=models.IntegerField(
                default=1,
                verbose_name='Número de Parcelas',
                help_text='1 para pagamento único, >1 para parcelado'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='percentual_primeira_parcela',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('50.00'),
                max_digits=5,
                verbose_name='% Primeira Parcela',
                help_text='Percentual da primeira parcela (para 2 parcelas)'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_primeira_parcela',
            field=models.DateField(
                default=timezone.now,
                verbose_name='Data Primeira Parcela'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='aceite_entrega',
            field=models.BooleanField(
                default=False,
                verbose_name='Aceite de Entrega',
                help_text='RF-15: Registro de aceite de entregas'
            ),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_aceite',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data do Aceite'
            ),
        ),
        
        # Alterar campos existentes
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(
                choices=[
                    ('lançado', 'Lançado'),
                    ('assinado', 'Assinado/Ativo'),
                    ('andamento', 'Em Andamento'),
                    ('cancelado', 'Cancelado'),
                    ('finalizado', 'Finalizado'),
                    ('suspenso', 'Suspenso'),
                ],
                default='lançado',
                max_length=20,
                verbose_name='Situação'
            ),
        ),
        
        
        # Atualizar Meta options
        migrations.AlterModelOptions(
            name='contrato',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos'
            },
        ),
    ]
