# Generated by Django 4.2.7 on 2025-09-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0007_auto_20250912_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='contratado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_parcela_inicial',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente solicitante', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, help_text='Valor total previsto do contrato', max_digits=14, verbose_name='Valor Previsto'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Apenas para PJ', max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cpf',
            field=models.CharField(blank=True, help_text='Apenas para PF', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddConstraint(
            model_name='prestador',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__isnull', False), ('tipo_pessoa', 'PF')), fields=('cpf',), name='unique_cpf_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='prestador',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), ('tipo_pessoa', 'PJ')), fields=('cnpj',), name='unique_cnpj_when_not_null'),
        ),
    ]
