# Generated by Django 4.2.7 on 2025-09-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_contrato_contratado_remove_contrato_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='aceite_entrega',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_aceite',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_primeira_parcela',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_parcelas',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='percentual_primeira_parcela',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_pagamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_previsto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_realizado',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Contratado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cpf_cnpj',
            field=models.CharField(blank=True, db_column='cpfcnpj', max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_parcela_inicial',
            field=models.DateField(blank=True, db_column='dataParcelaInicial', null=True, verbose_name='Data da Parcela Inicial'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_pessoa',
            field=models.IntegerField(blank=True, choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], db_column='tipoPessoa', null=True, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cod_ordem',
            field=models.IntegerField(db_column='codOrdem', verbose_name='Código da Ordem'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, db_column='dataFim', null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, db_column='dataInicio', null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='num_contrato',
            field=models.CharField(db_column='numContrato', max_length=20, primary_key=True, serialize=False, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aguardando Início'), ('2', 'Em andamento'), ('3', 'Paralisado'), ('4', 'Suspenso'), ('5', 'Cancelado'), ('6', 'Concluído')], max_length=20, null=True, verbose_name='Situação'),
        ),
    ]
